# Generated by Django 3.2.6 on 2023-02-22 09:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_number', models.IntegerField(default=0)),
                ('product', models.CharField(max_length=50)),
                ('start', models.DateTimeField(blank=True)),
                ('end', models.DateTimeField(blank=True)),
                ('description', models.TextField(max_length=70)),
                ('starting_bid', models.FloatField(default=0.01)),
                ('current_price', models.FloatField()),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('hash', models.CharField(default=None, max_length=64, null=True)),
                ('txId', models.CharField(default=None, max_length=66, null=True)),
                ('json_auction', models.TextField(default=None, max_length=5000, null=True)),
                ('active', models.BooleanField(default=True)),
                ('saved_on_redis', models.BooleanField(default=False)),
                ('manualClose', models.BooleanField(default=False)),
                ('photo', models.ImageField(upload_to='pics/%y/%m/%d/')),
                ('slug', models.SlugField(max_length=200)),
                ('current_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_winner', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_listings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='auction.auctionlisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=35)),
                ('auction_reference_code', models.IntegerField(default=0)),
                ('info_details_auction', models.TextField(max_length=3000)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, default=datetime.datetime(2023, 2, 22, 9, 19, 45, 954988, tzinfo=utc))),
                ('text', models.TextField(max_length=500)),
                ('auction_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auction.auctionlisting')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('auction_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auction.auctionlisting')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='accounts.profile')),
            ],
        ),
    ]
